import Head from 'next/head';
import clientPromise from '../lib/mongodb';
import { InferGetStaticPropsType } from 'next';

export async function getStaticProps(_context: any) {
  try {
    await clientPromise;
    return {
      props: { isConnected: true },
    };
  } catch (e) {
    console.error(e);
    return {
      props: { isConnected: false },
    };
  }
}

export default function Home({
  isConnected,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {isConnected ? (
        <div className='mx-auto text-align font-sans text-yellow-300 font-bold'>
          You are connected to MongoDB
        </div>
      ) : (
        <>Not connected</>
      )}
      <div></div>
      <main>Main</main>
    </>
  );
}
